// english-trainer-celpip — дані карток
// Формат однієї картки: { en, uk, cat, q, why }
//   en  = правильна відповідь (слово, що йде в пропуск).
//         Для "артикль не потрібен" → "-". Для синонімів → масив, напр. ["topics","subjects"].
//   uk  = українська підказка (значення).
//   cat = "prep" (прийменник) | "art" (артикль a/an/the/-) | "verb" (форма дієслова).
//   q   = речення, розбите на [до_пропуску, після_пропуску]. Пропуск стоїть між ними. Відповідь у q НЕ включай.
//   why = коротке пояснення українською (показується після відповіді).
//
// Щоб додати слово — допиши новий рядок-об'єкт у список нижче. HTML чіпати не треба.

window.WORDS = [
  // ── ПРИЙМЕННИКИ ──
  { en:"in", uk:"як на мене / на мою думку", cat:"prep",
    q:["","my opinion, the recreational park is the better choice."],
    why:"in my opinion — завжди in. НЕ on, НЕ according to." },
  { en:"on", uk:"ґрунтуючись на", cat:"prep",
    q:["Based ","my observations, burglaries have increased."],
    why:"based on — завжди on." },
  { en:"on", uk:"вплив на", cat:"prep",
    q:["More cameras would have little effect ","crime."],
    why:"effect / impact — завжди on." },
  { en:"on", uk:"витрачати гроші на", cat:"prep",
    q:["Tourists would spend money ","our local products."],
    why:"spend money on, не for." },
  { en:"for", uk:"відповідальний за", cat:"prep",
    q:["The BMW driver is responsible ","the accident."],
    why:"responsible завжди for, не to." },
  { en:"for", uk:"талант до (+ -ing)", cat:"prep",
    q:["You have a rare talent ","explaining complex ideas."],
    why:"talent for + герундій. Прийменник не виводиться логікою — завчити блоком." },
  { en:"at", uk:"досягати успіху в (+ -ing)", cat:"prep",
    q:["With your method I managed to excel ","conducting interviews."],
    why:"excel at + -ing. Не excel to / excel doing." },
  { en:"to", uk:"пишу вам (формально)", cat:"prep",
    q:["I am writing ","you regarding my recent order."],
    why:"write TO somebody. 'writing you' — помилка." },
  { en:"to", uk:"згідно з (джерелом)", cat:"prep",
    q:["According ","the report, burglaries rose last year."],
    why:"according to + джерело. З власною думкою — тільки 'in my opinion'." },
  { en:"in", uk:"у 2016 році", cat:"prep",
    q:["I first visited Bali ","2016."],
    why:"роки, місяці, пори року — in." },
  { en:"in", uk:"на півночі міста", cat:"prep",
    q:["Our office is located ","the north of the city."],
    why:"сторони світу — in the north / south." },
  { en:"to", uk:"доступ до", cat:"prep",
    q:["It is vital that children have access ","sports."],
    why:"access to something." },
  { en:"to", uk:"з нетерпінням чекати (+ -ing)", cat:"prep",
    q:["I look forward ","hearing from you."],
    why:"look forward to + -ing (hearing, не hear)." },
  { en:"on", uk:"вітання з нагоди", cat:"prep",
    q:["Congratulations ","your new position!"],
    why:"congratulations on, не with." },
  { en:"of", uk:"боятися", cat:"prep",
    q:["I am afraid ","the risks involved."],
    why:"afraid of." },
  { en:"of", uk:"замість", cat:"prep",
    q:["Instead ","a mall, our town needs a park."],
    why:"instead of." },
  { en:"of", uk:"керувати / відповідати за", cat:"prep",
    q:["She is in charge ","the whole project."],
    why:"in charge of." },
  { en:"of", uk:"на користь / за", cat:"prep",
    q:["I cannot vote in favour ","this plan."],
    why:"in favour of." },
  { en:"of", uk:"вдосталь / багато", cat:"prep",
    q:["There is plenty ","parking near the park."],
    why:"plenty of (і без a)." },
  { en:"on", uk:"на платформі / у застосунку", cat:"prep",
    q:["We could create a group ","Superbook."],
    why:"платформи й застосунки — on (on LinkedIn, on Instagram)." },
  { en:"to", uk:"надавати перевагу X над Y", cat:"prep",
    q:["I prefer the park ","the mall."],
    why:"prefer A to B." },
  { en:"for", uk:"вибачатися за", cat:"prep",
    q:["The manager apologized ","the delay."],
    why:"apologize for." },
  { en:"at", uk:"в університеті (навчається)", cat:"prep",
    q:["If my son weren't ","university, he would love this."],
    why:"at university / at school = навчання (без the). 'in the university' = фізично в будівлі." },
  { en:"to", uk:"надіслати на (адресу)", cat:"prep",
    q:["Please send your complaint ","this email address."],
    why:"send TO + адреса. 'on email' — помилка." },

  // ── АРТИКЛІ (a / an / the / -) ──
  { en:"-", uk:"порада — незлічуване", cat:"art",
    q:["You gave me ","valuable advice that changed everything."],
    why:"advice незлічуване → ніколи a, без множини. 'a piece of advice' якщо одна." },
  { en:"a", uk:"друг — злічуване", cat:"art",
    q:["I have ","friend in Bali who rents bungalows."],
    why:"friend злічуване, однина → a friend." },
  { en:"a", uk:"такий заклад — злічуване", cat:"art",
    q:["It would be wonderful to have such ","facility in our town."],
    why:"such a + злічуваний іменник в однині." },
  { en:"an", uk:"незвичний вибір — голосний звук", cat:"art",
    q:["Bali may be ","unusual choice for Christmas."],
    why:"перед голосним звуком → an (an unusual)." },
  { en:"-", uk:"меблі — незлічуване", cat:"art",
    q:["They sell ","second-hand furniture every Saturday."],
    why:"furniture незлічуване → без a, без множини." },
  { en:"-", uk:"обладнання — незлічуване", cat:"art",
    q:["The gym offers ","modern equipment."],
    why:"equipment незлічуване → без a/an, без множини." },
  { en:"-", uk:"на Різдво", cat:"art",
    q:["We travel for ","Christmas every year."],
    why:"свята — for Christmas (без the)." },
  { en:"-", uk:"до школи (навчання, загально)", cat:"art",
    q:["My kids go to ","school every morning."],
    why:"to school = навчання (без the). 'to the school' = у конкретну будівлю." },
  { en:"the", uk:"в парк (загальний)", cat:"art",
    q:["Let's go to ","park this weekend."],
    why:"park — загальне місце → the park." },
  { en:"-", uk:"у Walmart (власна назва)", cat:"art",
    q:["She went to ","Walmart yesterday."],
    why:"власна назва магазину/бренду → без артикля." },
  { en:"the", uk:"кількість (конкретна)", cat:"art",
    q:["This would decrease ","number of accidents."],
    why:"the number of = конкретна, визначена кількість → завжди the. (a number of = 'чимало', інше значення)." },
  { en:"the", uk:"ідея чогось", cat:"art",
    q:["","idea of a food market is interesting."],
    why:"the idea of — означена, конкретна ідея → the." },
  { en:"-", uk:"парк Morris (власна назва)", cat:"art",
    q:["The event will be held in ","Morris Park."],
    why:"власна назва парку → без the." },

  // ── ФОРМИ ДІЄСЛІВ ──
  { en:"left", uk:"should have + V3 (leave)", cat:"verb",
    q:["I called the manager, although I should have just ","at that point."],
    why:"modal + have + V3. leave → left. Не 'should have leave'." },
  { en:"was", uk:"узгодження часів у минулому (be)", cat:"verb",
    q:["The manager insisted that the steak ","perfect, until I asked him to taste it."],
    why:"історія в минулому → was, не is." },
  { en:"have", uk:"subjunctive (have — базова форма)", cat:"verb",
    q:["It is vital that every child ","access to sports."],
    why:"після 'it is vital/essential that' → базова форма, БЕЗ -s. Навіть з 'every child'." },
  { en:"be", uk:"subjunctive (be — базова форма)", cat:"verb",
    q:["I propose that each guest ","charged $30."],
    why:"після 'propose/suggest that' → be, не is." },
  { en:"build", uk:"subjunctive (build — базова форма)", cat:"verb",
    q:["I recommend that the council ","a recreational park."],
    why:"після 'recommend that' → базова форма, без -s (build, не builds)." },
  { en:"were", uk:"2nd conditional (be)", cat:"verb",
    q:["If this policy ","implemented, everyone would benefit."],
    why:"second conditional → were для всіх осіб (if it were)." },
  { en:"been", uk:"must have + V3 (be)", cat:"verb",
    q:["The locks must have ","outdated, which made break-ins easy."],
    why:"modal + have + V3. be → been. Не 'must had been'." },
  { en:["topics","subjects"], uk:"one of the most + множина", cat:"verb",
    q:["User Research was one of the most complex ","we studied."],
    why:"one of the most + ПРИКМЕТНИК + іменник у МНОЖИНІ." },
  { en:"to", uk:"struggle + to + дієслово (gather)", cat:"verb",
    q:["Before your method, I was struggling ","gather insights."],
    why:"struggle TO do. Не 'struggling gathering'." },
  { en:"as", uk:"such ... (as чи like?)", cat:"verb",
    q:["We need a green space, such ","a park with trees."],
    why:"such AS (не 'such...like')." }
];
