// english-trainer-celpip — дані карток
// Формат: { en, uk, cat, q, why }
//   en  = відповідь у пропуск. "-" = артикль не потрібен. Масив = кілька прийнятних, напр. ["topics","subjects"].
//   uk  = українська підказка (значення).
//   cat = "prep" | "art" | "verb".
//   q   = [до_пропуску, після_пропуску]. Відповідь у q НЕ включати.
//   why = коротке пояснення українською.

window.WORDS = [
  // ── ПРИЙМЕННИКИ ──
  { en:"in", uk:"як на мене / на мою думку", cat:"prep",
    q:["","my view, bike stands are a wiser investment than parking."],
    why:"in my opinion / in my view — завжди in. НЕ on." },
  { en:"on", uk:"ґрунтуючись на", cat:"prep",
    q:["Based ","last quarter's data, the lot is rarely full."],
    why:"based on — завжди on." },
  { en:"on", uk:"вплив на", cat:"prep",
    q:["A healthier commute would have a real effect ","staff wellbeing."],
    why:"effect / impact — завжди on." },
  { en:"on", uk:"витрачати гроші на", cat:"prep",
    q:["The company should spend its extra budget ","bike stands."],
    why:"spend money on, не for." },
  { en:"for", uk:"відповідальний за", cat:"prep",
    q:["The facilities manager is responsible ","approving the upgrade."],
    why:"responsible завжди for, не to." },
  { en:"for", uk:"талант до (+ -ing)", cat:"prep",
    q:["Logan has a real talent ","presenting technical ideas clearly."],
    why:"talent for + герундій. Завчити блоком." },
  { en:"at", uk:"досягати успіху в (+ -ing)", cat:"prep",
    q:["Our team has come to excel ","integrating AI into daily work."],
    why:"excel at + -ing. Не excel to / excel doing." },
  { en:"to", uk:"пишу вам (формально)", cat:"prep",
    q:["I am writing ","you regarding the upcoming conference."],
    why:"write TO somebody. 'writing you' — помилка." },
  { en:"to", uk:"згідно з (джерелом)", cat:"prep",
    q:["According ","our records, the lot is only 25% full most days."],
    why:"according to + джерело. З власною думкою — тільки 'in my opinion'." },
  { en:"on", uk:"у дати (on + дата/день)", cat:"prep",
    q:["Please let me know your availability ","the given dates."],
    why:"on the dates / on May 25. (не 'at the dates')." },
  { en:"in", uk:"у місяці / році", cat:"prep",
    q:["The Butterfly bridge was opened ","April this year."],
    why:"місяці, роки, пори року — in." },
  { en:"to", uk:"доступ до", cat:"prep",
    q:["Staff need easier access ","secure bike storage."],
    why:"access to something." },
  { en:"to", uk:"з нетерпінням чекати (+ -ing)", cat:"prep",
    q:["I look forward ","hearing your thoughts on this."],
    why:"look forward to + -ing (hearing, не hear)." },
  { en:"of", uk:"замість", cat:"prep",
    q:["Instead ","more parking, we could add thirty bike stands."],
    why:"instead of." },
  { en:"of", uk:"кількість чогось (the amount of)", cat:"prep",
    q:["The amount ","unused parking in our city keeps growing."],
    why:"the amount of + незлічуване." },
  { en:"of", uk:"керувати / відповідати за", cat:"prep",
    q:["She is in charge ","the conference logistics."],
    why:"in charge of." },
  { en:"at", uk:"подивитися на (take a look)", cat:"prep",
    q:["I would ask you to take another look ","the bike-stand option."],
    why:"take a look AT. (не 'look for' у цьому значенні)." },
  { en:"to", uk:"запросити когось (invite to)", cat:"prep",
    q:["I would like to invite you ","speak at our AI conference."],
    why:"invite somebody to do / to an event." },
  { en:"in", uk:"включено до (included in)", cat:"prep",
    q:["Is transport included ","the upgrade budget?"],
    why:"included IN — завжди. Не 'included into'." },
  { en:"on", uk:"наткнутися на (come across) — БЕЗ on", cat:"prep",
    q:["I came ","your proposal while reviewing the budget."],
    why:"come ACROSS something (без on). Тут пропуск = 'across'." },

  // ── АРТИКЛІ (a / an / the / -) ──
  { en:"-", uk:"інформація — незлічуване", cat:"art",
    q:["The exam does not give us ","specific information about what to prepare."],
    why:"information незлічуване → ніколи a, без множини." },
  { en:"-", uk:"знання — незлічуване", cat:"art",
    q:["Some fields require ","broad knowledge across many topics."],
    why:"knowledge незлічуване → без a." },
  { en:"a", uk:"команда — злічуване (work in a team)", cat:"art",
    q:["A research project improves your ability to work in ","team."],
    why:"work in a team (team злічуване → a)." },
  { en:"the", uk:"здатність (the ability to)", cat:"art",
    q:["This would improve ","ability of students to collaborate."],
    why:"the ability to do — означена → the." },
  { en:"a", uk:"проєкт — злічуване, однина", cat:"art",
    q:["I assume ","research project is more useful than an exam."],
    why:"research project злічуване → a research project (або множина projects)." },
  { en:"the", uk:"факультет (the faculty)", cat:"art",
    q:["I recommend that ","faculty choose the research option."],
    why:"the faculty — означений конкретний → the." },
  { en:"-", uk:"меблі — незлічуване", cat:"art",
    q:["The new office will not need ","extra furniture."],
    why:"furniture незлічуване → без a, без множини." },
  { en:"-", uk:"обладнання — незлічуване", cat:"art",
    q:["The bike room already has ","modern equipment."],
    why:"equipment незлічуване → без a/an." },
  { en:"the", uk:"маркетингова команда (the … team)", cat:"art",
    q:["","Marketing team offered to help you prepare."],
    why:"the Marketing team — конкретна команда → the." },
  { en:"a", uk:"рідкісна нагода — злічуване", cat:"art",
    q:["This is ","rare opportunity to showcase your work."],
    why:"opportunity злічуване → a rare opportunity." },
  { en:"-", uk:"до роботи (to work — навчання/праця)", cat:"art",
    q:["Many staff would cycle to ","work if there were stands."],
    why:"to work = на роботу (без the). 'to the work' — помилка." },
  { en:"-", uk:"власна назва компанії", cat:"art",
    q:["Developers from ","Google and Amazon will attend."],
    why:"власні назви компаній → без артикля." },

  // ── ФОРМИ ДІЄСЛІВ ──
  { en:"was", uk:"Past Simple з 'last month' (open)", cat:"verb",
    q:["The Butterfly bridge ","opened last month, so more staff now cycle."],
    why:"маркер минулого (last month) → Past Simple 'was opened', не 'has been opened'." },
  { en:"will", uk:"майбутній пасив (you … be granted)", cat:"verb",
    q:["If you accept, you ","be granted an extra vacation day."],
    why:"пропущено 'will': you WILL be granted. (і 'granted', без 'with')." },
  { en:"have", uk:"subjunctive (have — базова форма)", cat:"verb",
    q:["It is essential that every employee ","access to bike storage."],
    why:"після 'it is essential that' → базова форма, без -s." },
  { en:"be", uk:"subjunctive (be — базова форма)", cat:"verb",
    q:["I propose that the budget ","spent on bike stands."],
    why:"після 'propose that' → be, не is." },
  { en:"choose", uk:"subjunctive (choose — базова форма)", cat:"verb",
    q:["I recommend that the faculty ","the research project."],
    why:"після 'recommend that' → базова форма, без -s." },
  { en:"were", uk:"2nd conditional (be)", cat:"verb",
    q:["If the lot ","ever full, I would support more parking."],
    why:"second conditional → were для всіх осіб." },
  { en:"actively", uk:"прислівник, не прикметник (active)", cat:"verb",
    q:["Sarah and Jim started cycling more ","after the bridge opened."],
    why:"описуємо дію → прислівник 'actively', не 'active'." },
  { en:"examine", uk:"розглянути (examine, не 'examinate')", cat:"verb",
    q:["I would ask you to ","an alternative option first."],
    why:"дієслово — 'examine'. Слова 'examinate' не існує." },
  { en:"as", uk:"such ... (as чи like?)", cat:"verb",
    q:["Some fields, such ","medicine or aviation, do need exams."],
    why:"such AS (не 'such a / such like')." },
  { en:"Although", uk:"despite чи although? (+ ціле речення)", cat:"verb",
    q:["","I respect your idea, I would ask you to reconsider."],
    why:"перед ПІДМЕТ+ДІЄСЛОВО → Although (не Despite). І ніколи 'although...but'." }
];
